export const PRODUCER_MATCH_MODE = {
  EXACT: 'EXACT',
  FUZZY: 'FUZZY',
} as const

export const DEFAULT_PRODUCER_RULES: RegExp[] = [
  /(?:钢琴|Piano|Pno)/giu,
  /(?:电钢琴|ElectricPiano|Wurlitzer|Rhodes|EP)/giu,
  /(?:合成器|Synthesizer|Synths|Synth)/giu,
  /(?:键盘|Keyboard|Kybd|Keys)/giu,
  /(?:风琴|Organ|Org)/giu,
  /(?:大键琴|Harpsichord|Hpschd)/giu,
  /(?:手风琴|Accordion)/giu,
  /(?:特雷门琴|Theremin)/giu,
  /(?:电吉他|吉他|ElectricGuitar|AcousticGuitar|E\.Gtr|A\.Gtr|Guitar|Gtr)/giu,
  /(?:电贝斯|贝斯|ElectricBass|BassGuitar|E\.Bss|Bass|Bss)/giu,
  /(?:小提琴|提琴|Violin|Vln)/giu,
  /(?:中提琴|提琴|Viola|Vla)/giu,
  /(?:大提琴|提琴|Cello|Vc)/giu,
  /(?:低音提琴|提琴|DoubleBass|Contrabass|Cb)/giu,
  /(?:竖琴|Harp|Hrp)/giu,
  /(?:乌德琴|Oud)/giu,
  /(?:尤克里里|Ukulele|Uke)/giu,
  /(?:班卓琴|Banjo)/giu,
  /(?:曼陀林|Mandolin)/giu,
  /(?:鲁特琴|Lute)/giu,
  /(?:西塔琴|Sitar)/giu,
  /(?:班苏里笛|Bansuri)/giu,
  /(?:长笛|Flute|Fl)/giu,
  /(?:短笛|Piccolo|Picc)/giu,
  /(?:单簧管|Clarinet|Cl)/giu,
  /(?:低音单簧管|BassClarinet|B\.Cl)/giu,
  /(?:双簧管|Oboe|Ob)/giu,
  /(?:英国管|EnglishHorn|E\.Hn)/giu,
  /(?:巴松|Bassoon|Bsn)/giu,
  /(?:萨克斯|Saxophone|AltoSaxophone|TenorSaxophone|BaritoneSaxophone|A\.Sax|T\.Sax|B\.Sax|Sax)/giu,
  /(?:小号|Trumpet|Tpt)/giu,
  /(?:短号|Cornet|Cnt)/giu,
  /(?:长号|Trombone|Tbn)/giu,
  /(?:次中音号|Euphonium|Euph)/giu,
  /(?:圆号|FrenchHorn|Horn|Hn)/giu,
  /(?:大号|Tuba|Tba)/giu,
  /(?:架子鼓|DrumSet|Drums|Dr|鼓)/giu,
  /(?:打击乐|Percussion|Perc)/giu,
  /(?:定音鼓|Timpani|Timp)/giu,
  /(?:木琴|Xylophone|Xylo)/giu,
  /(?:马林巴|Marimba)/giu,
  /(?:颤音琴|Vibraphone|Vibes|Vib)/giu,
  /(?:康加鼓|Conga)/giu,
  /(?:邦戈鼓|Bongo)/giu,
  /(?:蒂姆巴尔鼓|Timbales)/giu,
  /(?:沙锤|Shaker)/giu,
  /(?:铃鼓|Tambourine|Tamb)/giu,
  /(?:钹|Cymbal)/giu,
  /(?:锣|Gong)/giu,
  /(?:口琴|Harmonica)/giu,
  /(?:古筝|Guzheng)/giu,
  /(?:琵琶|Pipa)/giu,
  /(?:二胡|Erhu)/giu,
  /(?:箫|Xiao)/giu,
  /(?:笛子|Dizi)/giu,
  /(?:唢呐|Suona)/giu,
  /(?:笙|Sheng)/giu,
  /(?:扬琴|Yangqin)/giu,
  /(?:采样器|Sampler)/giu,
  /(?:序列器|Sequencer)/giu,
  /(?:弦|String)/giu,
  /(?:巴乌|Bawu)/giu,
  /(?:阮|Ruan)/giu,
  /(?:乐器)/giu,

  /(?:艺人与制作|艺人|ArtistsandRepertoire)/giu,
  /(?:演奏者|乐手|乐师|SessionMusician|SessionPlayer|Musician|Performer)/giu,
  /(?:原唱|翻唱|配唱|合声)/giu,
  /(?:童声|男声|女声|人声|腔|念白)/giu,

  /(?:制作人|制作|Producer|Prod)/giu,
  /(?:执行制作人|执制|ExecutiveProducer|ExProd)/giu,
  /(?:协力制作人|协力|共同制作人|Co-Producer|CoProd|AssociateProducer)/giu,

  /(?:编曲|编|曲|Arranger|Arrangement|Arr)/giu,
  /(?:作曲|作|曲|Composer|Comp)/giu,
  /(?:作词|作|词|Lyricist|Lyr)/giu,
  /(?:乐谱|谱|Music)/giu,
  /(?:和声编写|和声|BackingVocalsArranger|BVArranger|BGVsArranger)/giu,
  /(?:编辑|AudioEditor|Edit|Editor)/giu,
  /(?:监制|监|Supervisor)/giu,
  /(?:人声编辑|VocalEditor|VocalEdit)/giu,
  /(?:音效设计|音效|SoundEffectsDesigner|SFXDesigner)/giu,
  /(?:演唱|唱)/giu,
  /(?:Rap)/giu,

  /(?:题字|文案)/giu,
  /(?:封面|海报|图绘|映像|封|Cover|Image)/giu,
  /(?:脚本|分镜|视频|Video|PV|MV|CG)/giu,
  /(?:OP|SP)/giu,
  /(?:视觉设计|视觉|设计)/giu,

  /(?:编调|编程|Programming|Programmer|Prog)/giu,
  /(?:音乐总监|MusicDirector|MD)/giu,
  /(?:配器|Orchestrator|Orchestration|Orch)/giu,
  /(?:指挥|Conductor|Cond)/giu,

  /(?:工程师|Engineer|Eng)/giu,
  /(?:音响工程师|音响|声工|AudioEngineer|SoundEngineer)/giu,
  /(?:声音设计师|声音|声设|SoundDesigner|SoundDes)/giu,
  /(?:母带工程师|母带|MasteringEngineer|MasterEngineer|Mst)/giu,
  /(?:助理工程师|助工|助理|AssistantEngineer|AsstEng|A\.Eng)/giu,
  /(?:跟踪工程师|TrackingEngineer|TrackingEng)/giu,
  /(?:监听工程师|监听|MonitorEngineer)/giu,

  /(?:录音室经理|录音室|StudioManager)/giu,
  /(?:录音师|录音|RecordingEngineer|Recordist|Rec)/giu,
  /(?:重混音师|Remixer|Remixedby|Remix)/giu,
  /(?:混音|分轨|贴混|混|MixingEngineer|Mixer|Mix)/giu,
  /(?:修音师|修音)/giu,
  /(?:拟音师|拟音|FoleyArtist)/giu,
  /(?:抄谱员|抄谱|Copyist)/giu,
  /(?:乐谱管理员|Librarian)/giu,
  /(?:扒谱员|扒谱|Transcriber|Trans)/giu,
  /(?:节拍制作人|节拍|Beatmaker|BeatMaker)/giu,
  /(?:吉他技师|GuitarTech)/giu,
  /(?:鼓技师|DrumTech)/giu,
  /(?:舞台监督|StageManager)/giu,
  /(?:灯光师|LightingDesigner|LightTech)/giu,
  /(?:音控师|FOHEngineer|FrontofHouseEngineer)/giu,
  /(?:调音师|调音|调音师|SoundMixer|LiveSoundEngineer)/giu,
  /(?:后期制作|后期|Post-production|PostProd)/giu,
  /(?:母带后期|PostMastering)/giu,
  /(?:调校|调教)/giu,
  /(?:美工|美术|曲绘)/giu,

  /(?:项目统筹|统筹|项目|ProjectCoordinator|Coordinator)/giu,
  /(?:发行|发布|Release)/giu,
  /(?:出品|Produced)/giu,
  /(?:宣传|推广|宣发|宣推|营销)/giu,
  /(?:版权|Copyright)/giu,
  /(?:承办单位|承办|单位|业务|策划|企划|策监)/giu,
  /(?:支持|鸣谢)/giu,
] as const

export const DEFAULT_PRODUCER_RULES_QUICK_KEYWORDS: string[] = (() => {
  const src = DEFAULT_PRODUCER_RULES.map((r) => r.source).join(' ')
  const raw = src.match(/[A-Za-z\u4e00-\u9fff]{2,}/g) || []

  const uniq = Array.from(new Set(raw.map((s) => s.toLowerCase())))
  uniq.sort((a, b) => b.length - a.length)

  return uniq
})()
