export const DEFAULT_PRODUCER_RULES: RegExp[] = [
  // Instruments
  /(?:钢琴|Pno|Piano)/giu,
  /(?:电钢琴|EP|Electric\s*Piano|Rhodes|Wurlitzer)/giu,
  /(?:合成器|Synth|Synthesizer|Synths)/giu,
  /(?:键盘|Kybd|Keyboard|Keys)/giu,
  /(?:风琴|Org|Organ)/giu,
  /(?:大键琴|Hpschd|Harpsichord)/giu,
  /(?:手风琴|Accordion)/giu,
  /(?:吉他|Gtr|Guitar|Electric\s*Guitar|Acoustic\s*Guitar|E\.Gtr|A\.Gtr)/giu,
  /(?:贝斯|Bss|Bass|Bass\s*Guitar|Electric\s*Bass|E\.Bss)/giu,
  /(?:小提琴|提琴|Vln|Violin)/giu,
  /(?:中提琴|提琴|Vla|Viola)/giu,
  /(?:大提琴|提琴|Vc|Cello)/giu,
  /(?:低音提琴|提琴|Cb|Contrabass|Double\s*Bass)/giu,
  /(?:竖琴|Hrp|Harp)/giu,
  /(?:尤克里里|Uke|Ukulele)/giu,
  /(?:班卓琴|Banjo)/giu,
  /(?:曼陀林|Mandolin)/giu,
  /(?:鲁特琴|Lute)/giu,
  /(?:西塔琴|Sitar)/giu,
  /(?:长笛|Fl|Flute)/giu,
  /(?:短笛|Picc|Piccolo)/giu,
  /(?:单簧管|Cl|Clarinet)/giu,
  /(?:低音单簧管|B\.Cl|Bass\s*Clarinet)/giu,
  /(?:双簧管|Ob|Oboe)/giu,
  /(?:英国管|E\.Hn|English\s*Horn)/giu,
  /(?:巴松|Bsn|Bassoon)/giu,
  /(?:萨克斯|Sax|Saxophone|Alto\s*Saxophone|Tenor\s*Saxophone|Baritone\s*Saxophone|A\.Sax|T\.Sax|B\.Sax)/giu,
  /(?:小号|Tpt|Trumpet)/giu,
  /(?:短号|Cnt|Cornet)/giu,
  /(?:长号|Tbn|Trombone)/giu,
  /(?:次中音号|Euph|Euphonium)/giu,
  /(?:圆号|Hn|French\s*Horn|Horn)/giu,
  /(?:大号|Tba|Tuba)/giu,
  /(?:鼓|Dr|Drums|Drum\s*Set|架子鼓)/giu,
  /(?:打击乐|Perc|Percussion)/giu,
  /(?:定音鼓|Timp|Timpani)/giu,
  /(?:木琴|Xylo|Xylophone)/giu,
  /(?:马林巴|Marimba)/giu,
  /(?:颤音琴|Vib|Vibraphone|Vibes)/giu,
  /(?:康加鼓|Conga)/giu,
  /(?:邦戈鼓|Bongo)/giu,
  /(?:蒂姆巴尔鼓|Timbales)/giu,
  /(?:沙锤|Shaker)/giu,
  /(?:铃鼓|Tamb|Tambourine)/giu,
  /(?:钹|Cymbal)/giu,
  /(?:锣|Gong)/giu,
  /(?:口琴|Harmonica)/giu,
  /(?:古筝|Guzheng)/giu,
  /(?:琵琶|Pipa)/giu,
  /(?:二胡|Erhu)/giu,
  /(?:箫|Xiao)/giu,
  /(?:笛子|Dizi)/giu,
  /(?:唢呐|Suona)/giu,
  /(?:笙|Sheng)/giu,
  /(?:扬琴|Yangqin)/giu,
  /(?:采样器|Sampler)/giu,
  /(?:序列器|Sequencer)/giu,

  // Producer
  /(?:艺人|艺人与制作|A&R|Artists\s*and\s*Repertoire)/giu,
  /(?:乐手|乐师|演奏者|Session\s*Musician|Session\s*Player|Musician|Performer)/giu,
  /(?:原唱|翻唱|配唱|艺人|合声)/giu,
  /(?:男声|女声|人声|童声|腔|念白)/giu,

  /(?:制作人|制作|Prod|Producer)/giu,
  /(?:执行制作人|执制|Ex\s*Prod|Executive\s*Producer)/giu,
  /(?:协力制作人|协力|共同制作人|Co-Producer|Co\s*Prod|Associate\s*Producer)/giu,

  /(?:编曲|编|曲|歌|Arr|Arranger|Arrangement)/giu,
  /(?:作曲|作|曲|歌|Comp|Composer)/giu,
  /(?:作词|词|Lyr|Lyricist)/giu,
  /(?:乐谱|谱|Music|Spectrum)/giu,
  /(?:和声编写|和声|BV\s*Arranger|Backing\s*Vocals\s*Arranger|BGVs\s*Arranger)/giu,
  /(?:编辑|Edit|Editor|Audio\s*Editor)/giu,
  /(?:监制|监|Supervisor)/giu,
  /(?:人声编辑|Vocal\s*Edit|Vocal\s*Editor)/giu,
  /(?:音效设计|音效|SFX\s*Designer|Sound\s*Effects\s*Designer)/giu,
  /(?:Rap)/giu,

  /(?:文案|题字)/giu,
  /(?:封面|封|海报|图绘|映像|Cover|Image)/giu,
  /(?:视频|脚本|分镜|Video|PV|MV|CG)/giu,
  /(?:OP|SP)/giu,
  /(?:视觉设计|设计|视觉)/giu,

  /(?:编程|编调|Prog|Programmer|Programming)/giu,
  /(?:音乐总监|MD|Music\s*Director)/giu,
  /(?:配器|Orch|Orchestrator|Orchestration)/giu,
  /(?:指挥|Cond|Conductor)/giu,

  /(?:工程师|Eng|Engineer)/giu,
  /(?:音响工程师|声工|音响|Sound\s*Engineer|Audio\s*Engineer)/giu,
  /(?:声音设计师|声设|声音|Sound\s*Des|Sound\s*Designer)/giu,
  /(?:母带工程师|母带|Mst|Master|Mastering\s*Engineer|Master\s*Engineer)/giu,
  /(?:助理工程师|助工|助理|Asst\s*Eng|Assistant\s*Engineer|A\.Eng)/giu,
  /(?:跟踪工程师|Tracking\s*Eng|Tracking\s*Engineer)/giu,
  /(?:监听工程师|监听|Monitor\s*Engineer)/giu,

  /(?:录音室经理|录音室|Studio\s*Manager)/giu,
  /(?:录音师|录音|Rec|Recording\s*Engineer|Recordist)/giu,
  /(?:重混音师|Remix|Remixer|Remixed\s*by)/giu,
  /(?:混音|混|分轨|贴混|Mix|Mixer|Mixing\s*Engineer)/giu,
  /(?:修音师|修音)/giu,
  /(?:拟音师|拟音|Foley\s*Artist)/giu,
  /(?:抄谱员|抄谱|Copyist)/giu,
  /(?:乐谱管理员|Librarian)/giu,
  /(?:扒谱员|Trans|Transcriber)/giu,
  /(?:节拍制作人|节拍|Beatmaker|Beat\s*Maker)/giu,
  /(?:吉他技师|Guitar\s*Tech)/giu,
  /(?:鼓技师|Drum\s*Tech)/giu,
  /(?:舞台监督|Stage\s*Manager)/giu,
  /(?:灯光师|Lighting\s*Designer|Light\s*Tech)/giu,
  /(?:音控师|FOH\s*Engineer|Front\s*of\s*House\s*Engineer)/giu,
  /(?:调音师|调音|Sound\s*Mixer|Live\s*Sound\s*Engineer)/giu,
  /(?:后期制作|后期|Post-production|Post\s*Prod)/giu,
  /(?:母带后期|Post\s*Mastering)/giu,
  /(?:调校|调教)/giu,

  /(?:项目统筹|统筹|项目|Project\s*Coordinator|Coordinator)/giu,
  /(?:发行|发布|Release)/giu,
  /(?:出品|Produced)/giu,
  /(?:宣传|推广|宣发|宣推)/giu,
  /(?:版权|Copyright)/giu,
  /(?:承办单位|承办|单位|业务|策划|企划|策监)/giu,
  /(?:支持|鸣谢)/giu,
] as const

export const DEFAULT_PRODUCER_RULES_QUICK_KEYWORDS: string[] = (() => {
  const src = DEFAULT_PRODUCER_RULES.map((r) => r.source).join(' ')
  const raw = src.match(/[A-Za-z\u4e00-\u9fff]{2,}/g) || []

  const uniq = Array.from(new Set(raw.map((s) => s.toLowerCase())))
  uniq.sort((a, b) => b.length - a.length)

  return uniq
})()

console.log(DEFAULT_PRODUCER_RULES_QUICK_KEYWORDS)
