name: Release

on:
  push:
    tags:
      - 'v*' # e.g. v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Update Npm
        run: npm i -g npm@latest

      - name: Install Dependencies
        run: pnpm install

      - name: Build Code
        run: pnpm run build

      - name: Publish Package
        run: pnpm run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build Current Change Log
        run: pnpm run build-current-change-log

      - name: Create Github Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: ./CURRENT_CHANGELOG.md
          prerelease: false
          draft: false
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
